_wandb:
    value:
        cli_version: 0.24.0
        e:
            rphp9vd9inkjepv01qo72lu2agpyrtk1:
                args:
                    - --config
                    - configs/default.yaml
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "441788145664"
                        used: "146413858816"
                email: udusaa@gmail.com
                executable: /home/vladlanda/miniconda3/envs/py311pip/bin/python3.11
                git:
                    commit: 8509bcbcacd545b12dd111b76d3ed3835e33cb4c
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-57aa516d-afe6-62cd-5113-0c88877afa1a
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-48f2f125-8364-0f1f-9e65-bbdac11e209f
                host: vladlanda
                memory:
                    total: "100674203648"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /media/vladlanda/T5EVO/Postdoc/Tel Aviv/Code/DDIM-LI/train.py
                python: CPython 3.11.14
                root: /media/vladlanda/T5EVO/Postdoc/Tel Aviv/Code/DDIM-LI
                startedAt: "2026-03-14T08:06:47.194211Z"
                writerId: rphp9vd9inkjepv01qo72lu2agpyrtk1
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 100
            "2":
                - 1
                - 100
            "3":
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
P_mean:
    value: -1.2
P_std:
    value: 1.2
T_in:
    value: 6
T_out:
    value: 36
amp:
    value: true
attn_resolutions:
    value:
        - 16
        - 8
base_channels:
    value: 128
batch_size:
    value: 4
cfg_drop_prob:
    value: 0.15
cfg_scale:
    value: 1.5
channel_mults:
    value:
        - 1
        - 2
        - 3
        - 4
channels:
    value:
        - ir
        - li
        - ch0
        - ch1
config:
    value: configs/default.yaml
dropout:
    value: 0.1
dt_min:
    value: 10
ema_decay:
    value: 0.9999
emb_dim:
    value: 512
epochs:
    value: 200
grad_clip:
    value: 1
img_size:
    value:
        - 256
        - 256
li_weight:
    value: 3
lr:
    value: 0.0001
max_samples:
    value: 100
n_members:
    value: 10
num_res_blocks:
    value: 2
num_workers:
    value: 4
output_dir:
    value: outputs/run_test
resume:
    value: false
sigma_data:
    value: 0.5
sigma_max:
    value: 80
sigma_min:
    value: 0.002
spectral_weight:
    value: 0.1
test_roots:
    value:
        - /home/vladlanda/Workplace/LI-DATASETS/small/central_africa_2
train_roots:
    value:
        - /home/vladlanda/Workplace/LI-DATASETS/small/central_africa_1
train_val_split:
    value: 0.7
val_every:
    value: 5
val_samples:
    value: 5
wandb_project:
    value: DDIM-LI
weight_decay:
    value: 0.0001
